import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import TopNavbar from '../components/TopNavbar'
import Services from '../components/Services'
import Quote from '../components/Quote'
import Portfolio from '../components/Portofolio'
import Footer from '../components/Footer'
import {
	createTheme,
	styled,
	Navbar,
} from '@nextui-org/react'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Next French Touch</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<TopNavbar />
			<Hero />
			<Services />
			<Quote />
			<Portfolio />
			<Footer />
		</div>
	)
}

const Layout = styled('div', {
	width: '100%',
})
